services:
  resolver-01:
    build: .
    container_name: resolver-01
    restart: unless-stopped
    networks:
      dns-net:
        ipv4_address: 10.89.10.10
    volumes:
      - ./config/unbound.conf:/etc/unbound/unbound.conf:z
      - ./config/root.hints:/etc/unbound/root.hints:z

networks:
  dns-net:
    external: true
